services:
  worker:
    build: .
    container_name: sb_worker
    env_file: .env
    environment:
      - SEARCHBOOST_REDIS_HOST=sb_redis
      - SEARCHBOOST_AI_HOST=sb_ollama
      - SEARCHBOOST_SEARCH_HOST=sb_searxng
      - PYTHONBUFFERED=1
      - SEARCHBOOST_REDIS_PASSWORD=${REDIS_PASSWORD:-searchboost_pass}
    volumes:
      - .:/app
    depends_on:
      - redis
      - ollama
      - searxng
    restart: always

  redis:
    image: redis:7.4-alpine
    container_name: sb_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-searchboost_pass} --appendonly yes
    volumes:
      - redis_data:/data
    restart: always

  ollama:
    image: ollama/ollama
    container_name: sb_ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

  searxng:
    image: searxng/searxng
    container_name: sb_searxng
    ports:
      - "${SEARXNG_PORT:-8080}:8080"
    volumes:
      - ./configs:/etc/searxng:ro
    environment:
      - SEARXNG_BASE_URL=http://sb_searxng:${SEARXNG_PORT:-8080}/
      - SEARXNG_SETTINGS_PATH=/etc/searxng/searxng_settings.yml
    restart: always

volumes:
  ollama_data:
  redis_data: