services:
  sb_warden:
    build: ./searchboost_warden
    container_name: sb_warden
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/usr/src/app/logs
    environment:
      - RUST_LOG=info
  worker:
    build: .
    container_name: sb_worker
    env_file: .env
    environment:
      - SEARCHBOOST_REDIS_HOST=sb_redis
      - SEARCHBOOST_AI_HOST=sb_ollama
      - SEARCHBOOST_SEARCH_HOST=sb_searxng
      - PYTHONBUFFERED=1
      - SEARCHBOOST_REDIS_PASSWORD=${REDIS_PASSWORD:-searchboost_pass}
      - PYTHONPATH=/app
    command : arq searchboost_src.worker.WorkerSettings
    volumes:
      - ./searchboost_service:/app
    depends_on:
      - redis
      - ollama
      - searxng
      - db
    restart: always

  redis:
    image: redis:7.4-alpine
    container_name: sb_redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-searchboost_pass} --appendonly yes
    volumes:
      - redis_data:/data
    restart: always

  ollama:
    image: ollama/ollama
    container_name: sb_ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

  searxng:
    image: searxng/searxng
    container_name: sb_searxng
    ports:
      - "${SEARXNG_PORT:-8080}:8080"
    volumes:
      - ./configs:/etc/searxng:ro
    environment:
      - SEARXNG_BASE_URL=http://sb_searxng:${SEARXNG_PORT:-8080}/
      - SEARXNG_SETTINGS_PATH=/etc/searxng/searxng_settings.yml
    restart: always

  db:
      image: postgres:16-alpine
      container_name: sb_db
      restart: always
      environment:
        - POSTGRES_USER=${DB_USER:-searchboost}
        - POSTGRES_PASSWORD=${DB_PASSWORD:-searchboost_pass}
        - POSTGRES_DB=${DB_NAME:-searchboost_db}
      ports:
        - "${POSTGRES_PORT:-5432}:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
volumes:
  ollama_data:
  redis_data:
  postgres_data: