services:
  ollama:
    image: ollama/ollama
    container_name: sb_ollama
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

  searxng:
    image: searxng/searxng
    container_name: sb_searxng
    ports:
      - "${SEARXNG_PORT:-8080}:8080"
    environment:
      - SEARXNG_BASE_URL=http://localhost:${SEARXNG_PORT:-8080}/
    restart: always

volumes:
  ollama_data: